= Budgetplaner
ifndef::imagesdir[:imagesdir: images]

Lind Arifi, Leonie Findenig, Lena Graßauer, Leona Feichtinger

== Überblick

=== 1. Datenmodell
=== 2. Anwendungsfalldiagramm
=== 3. Funktionsweise des Nachhaltigkeitstrackers
=== 4. Problemlösung durch die Anwendung

***

== Datenmodell - UML-Klassendiagramm

***

=== Klassendiagram

[plantuml]
----
@startuml
@startuml
class Budget {
- ID: int
- Monat: String
- Einkommen: float
- Fixkosten: float
- Verfügbares Budget: float
}

class Ausgabe{
- ID: int
- Betrag: float
- Kategorie: String
- Datum: Date
- BudgetID: int
}

class Nutzer {
- ID: int
- Name: String
- Email: String
- TelNr: String
}

Budget <-- Ausgabe
Nutzer <-- Budget
@enduml
----


***

=== Anwendungsfalldiagramm

[plantuml]
----
@startuml
actor Nutzer

rectangle "Budgetplaner" {
usecase "Einnahmen und Fixkosten eingeben" as UC1
usecase "Ausgaben erfassen" as UC2
usecase "Budgetanalyse anzeigen" as UC3
}

Nutzer -- UC1
Nutzer -- UC2
Nutzer -- UC3
@enduml
----

***

== Problemstellung und Lösungsansatz
***
=== Problem:
Viele Konsumenten sind unsicher über die Nachhaltigkeit von Produkten und haben Schwierigkeiten, umweltfreundliche Optionen schnell zu finden.

=== Lösung:
Der Nachhaltigkeitstracker ermöglicht eine einfache Suche nach nachhaltigen Produkten und bietet transparente Informationen zu deren ökologischen Eigenschaften.


***

== Aufgabenstellung und Funktionen
***

=== Ziel:
Entwicklung einer Anwendung zur Bewertung der Nachhaltigkeit von Produkten. Nutzer sollen über eine Datenbank nachhaltige Produkte finden können.

***

=== Hauptfunktionen:
- **Datenbank:** Speicherung relevanter Produktdaten
- **Produktsuche:** Manuelle Suche oder Barcode-Scan
- **Nachhaltigkeitsbewertung:** Anzeige von Umwelt- und Nachhaltigkeitsinformationen

***

== Fazit und Ausblick
***

=== Fazit
Der Nachhaltigkeitstracker fördert umweltbewusste Kaufentscheidungen und bietet eine transparente Übersicht über Produkte.

=== Ausblick:
Weitere Erweiterungen könnten eine Bewertung durch Nutzer oder Kooperationen mit Herstellern umfassen.


