= Budgetplaner
ifndef::imagesdir[:imagesdir: images]

Lind Arifi, Leonie Findenig, Lena Graßauer, Leona Feichtinger

== Überblick

=== 1. Datenmodell
=== 2. Anwendungsfalldiagramm
=== 3. Funktionsweise des Nachhaltigkeitstrackers
=== 4. Problemlösung durch die Anwendung

***

== Datenmodell - UML-Klassendiagramm

***

=== Klassendiagram

[plantuml]
----
@startuml
@startuml
class Budget {
- ID: int
- Monat: String
- Einkommen: float
- Fixkosten: float
- Verfügbares Budget: float
}

class Ausgabe{
- ID: int
- Betrag: float
- Kategorie: String
- Datum: Date
- BudgetID: int
}

class Nutzer {
- ID: int
- Name: String
- Email: String
- TelNr: String
}

Budget <-- Ausgabe
Nutzer <-- Budget
@enduml
----


***

=== Anwendungsfalldiagramm

[plantuml]
----
@startuml
actor Nutzer

rectangle "Budgetplaner" {
usecase "Einnahmen und Fixkosten eingeben" as UC1
usecase "Ausgaben erfassen" as UC2
usecase "Budgetanalyse anzeigen" as UC3
}

Nutzer -- UC1
Nutzer -- UC2
Nutzer -- UC3
@enduml
----

***

== Problemstellung und Lösungsansatz
***
=== Problem:
Viele Menschen haben Schwierigkeiten, ihre Finanzen zu überblicken und ein Budget effizient zu verwalten.

=== Lösung:
Der Budgetplaner hilft Nutzern, ihre Einnahmen und Ausgaben einfach zu erfassen, ihr Budget zu überwachen und bessere finanzielle Entscheidungen zu treffen.

***

== Aufgabenstellung und Funktionen
***

=== Ziel:
Entwicklung einer Anwendung zur Verwaltung und Analyse von Einnahmen und Ausgaben, um eine bessere finanzielle Planung zu ermöglichen.
***

=== Hauptfunktionen:
- **Budgetverwaltung:** Erfassen von Einnahmen, Fixkosten und variablen Ausgaben
- **Kategorien:** Ausgaben in verschiedene Kategorien einteilen


***

== Fazit und Ausblick
***

=== Fazit
Der Budgetplaner erleichtert die Verwaltung der persönlichen Finanzen, bietet eine bessere Kostenkontrolle und hilft bei der Erreichung finanzieller Ziele.

=== Ausblick:
Weitere Erweiterungen könnten eine Bewertung durch Nutzer oder Kooperationen mit Herstellern umfassen.


