= Nachhaltigkeitstracker
ifndef::imagesdir[:imagesdir: images]

Lind Arifi, Leonie Findenig, Lena Graßauer, Leona Feichtinger

== Überblick

=== 1. Datenmodell
=== 2. Anwendungsfalldiagramm
=== 3. Funktionsweise des Nachhaltigkeitstrackers
=== 4. Problemlösung durch die Anwendung

---

== Datenmodell - UML-Klassendiagramm

[plantuml]
----
@startuml
class Produkt {
    - ID: int
    - Name: String
    - Hersteller: String
    - Herkunftsland: String
    - Nachhaltigkeitsscore: float
    - KategorieID
    - BarcodeID: int
}

class ProduktKategorie{
    - ID: int
    - Bezeichnung: string
}

class Barcode {
    - ID: int
    - Code: String
}

class Nutzer {
    - ID: int
    - Name: String
    - Email: String
    - TelNr: String
}

Produkt <--  Barcode
Produkt <-- ProduktKategorie
@enduml
----


---

== Anwendungsfalldiagramm

[plantuml]
----
@startuml
actor Kunde

rectangle "Nachhaltigkeitstracker" {
  usecase "Produkt scannen" as UC1
  usecase "Nachhaltigkeitsbewertung anzeigen" as UC2
  usecase "Produkt manuell suchen" as UC3
}

Kunde -- UC1
Kunde -- UC2
Kunde -- UC3

@enduml
----


---

== Problemstellung und Lösungsansatz
***
=== Problem:
Viele Konsumenten sind unsicher über die Nachhaltigkeit von Produkten und haben Schwierigkeiten, umweltfreundliche Optionen schnell zu finden.

=== Lösung:
Der Nachhaltigkeitstracker ermöglicht eine einfache Suche nach nachhaltigen Produkten und bietet transparente Informationen zu deren ökologischen Eigenschaften.


---

== Aufgabenstellung und Funktionen
***

=== Ziel:
Entwicklung einer Anwendung zur Bewertung der Nachhaltigkeit von Produkten. Nutzer sollen über eine Datenbank nachhaltige Produkte finden können.
***

=== Hauptfunktionen:
- **Datenbank:** Speicherung relevanter Produktdaten
- **Produktsuche:** Manuelle Suche oder Barcode-Scan
- **Nachhaltigkeitsbewertung:** Anzeige von Umwelt- und Nachhaltigkeitsinformationen


---

== Fazit und Ausblick
***
Der Nachhaltigkeitstracker fördert umweltbewusste Kaufentscheidungen und bietet eine transparente Übersicht über Produkte.

=== Ausblick:
Weitere Erweiterungen könnten eine Bewertung durch Nutzer oder Kooperationen mit Herstellern umfassen.


---
