= Budgetplaner
ifndef::imagesdir[:imagesdir: images]

Lind Arifi, Leonie Findenig, Lena Graßauer, Leona Feichtinger

== Überblick

=== 1. Datenmodell
=== 2. Anwendungsfalldiagramm
=== 3. Funktionsweise des Nachhaltigkeitstrackers
=== 4. Problemlösung durch die Anwendung



== Datenmodell - UML-Klassendiagramm


=== Klassendiagram

[plantuml, diagram-klassendiagramm, svg]
----
@startuml
class Budget {
  - ID: int
  - Monat: String
  - Einkommen: float
  - Fixkosten: float
  - Verfügbares Budget: float
}

class Ausgabe {
  - ID: int
  - Betrag: float
  - Kategorie: String
  - Datum: Date
  - BudgetID: int
}

class Nutzer {
  - ID: int
  - Name: String
  - Email: String
  - TelNr: String
}

Budget <-- Ausgabe
Nutzer <-- Budget
@enduml
----

----




=== Anwendungsfalldiagramm

[plantuml,target=diagram-1, format=svg]
----
@startuml
actor Nutzer

rectangle "Budgetplaner" {
usecase "Einnahmen und Fixkosten eingeben" as UC1
usecase "Ausgaben erfassen" as UC2
usecase "Budgetanalyse anzeigen" as UC3
}

Nutzer -- UC1
Nutzer -- UC2
Nutzer -- UC3
@enduml
----



== Problemstellung und Lösungsansatz

=== Problem:
Viele Personen sind sich am Ende des Monats unsicher wofür sie  ihr Geld ausgegeben haben.

=== Lösung:
Der Budgetplanner ist eine Web Aplikation um am Ende des Monats eine klare Übersicht über seine Finanzen zu haben. Das man aber nicht jedes Monat nur den Schock hat wie viel man ausgegeben hat in gewissen Bereichen, gitb es auch einen Planner.


== Aufgabenstellung und Funktionen

=== Ziel:
Entwicklung einer Anwendung zur Verwaltung und Analyse von Einnahmen und Ausgaben, um eine bessere finanzielle Planung zu ermöglichen.


=== Hauptfunktionen:
- **Datenbank:** Einlesen der Bankdaten: Konto Auszüge und Eingänge 
- **Diagramm:** Ein Diagramm das die Ausgaben in gewisse Bereiche einteilt und abbildet 
- **Planner:** Eien Funktion zum Plannen der AUsgaben für das Monat 



== Fazit und Ausblick


=== Fazit
Der Budgetplaner erleichtert die Verwaltung der persönlichen Finanzen, bietet eine bessere Kostenkontrolle und hilft bei der Erreichung finanzieller Ziele.

=== Ausblick:
Weitere Erweiterungen könnten eine Bewertung durch Nutzer oder Kooperationen mit Herstellern umfassen.= Budgetplaner
ifndef::imagesdir[:imagesdir: images]

