= Nachhaltigkeitstracker
FIndenig Leonie, Lena Graßauer, Lind Arifi

=== Ausgangssituation:

Das Unternehmen GoodFood in Leonding bietet eine vielfältige Auswahl an Lebensmitteln an, beschäftigt 20 Mitarbeiter und legt großen Wert auf Umweltbewusstsein.

=== Problemstellung:


Wir möchten, dass unsere Kunden auf einen Blick sehen können, wie nachhaltig unsere Produkte wirklich sind und so einen transparenteren Einblick in unser Unternehmen gewinnen. Derzeit ist es jedoch sehr zeitaufwendig, bei jedem einzelnen Produkt nachzuprüfen, wie nachhaltig es tatsächlich ist. Dadurch hinterfragen unsere Kunden häufiger unsere Bemühungen um Nachhaltigkeit.

=== Ziel:
Wir möchten, dass unsere Kunden auf einen Blick sehen können, wie nachhaltig unsere Produkte wirklich sind und so einen transparenteren Einblick in unser Unternehmen gewinnen.
Derzeit ist es jedoch sehr zeitaufwendig, bei jedem einzelnen Produkt nachzuprüfen, wie nachhaltig es tatsächlich ist.
Dadurch hinterfragen unsere Kunden häufiger unsere Bemühungen um Nachhaltigkeit.


=== Aufgabenstellung

Eine App oder WebApp womit man mit Hilfe eines Barcode Scanners sofort die Inhaltsstoffe, Herkunft und Nachhaltigkeitsbewertung sehen kann.
Das erleichtert es unseren Kunden zu sehen das wir uns wirklich mit Nachhaltigkeit beschäftigen und Ihnen auch Einblicke dazu gewähren.

==== Funktionale Anforderungen


==== Nichtfunktionale Anforderungen (NFA)

=== Mengengerüst
=== Rahmenbedingungen


