= Nachhaltigkeitstracker
FIndenig Leonie, Lena Graßauer, Lind Arifi

=== Ausgangssituation:
Viele Menschen haben Schwierigkeiten, ihre Finanzen im Blick zu behalten und ein effektives Budget zu verwalten. Besonders unerwartete Ausgaben oder fehlende Transparenz über laufende Kosten führen oft zu finanziellen Engpässen.

=== Problemstellung:

Wir möchten, dass unsere Nutzer auf einen Blick sehen können, wie viel Budget ihnen zur Verfügung steht, welche Ausgaben sie haben und wie sie ihre Finanzen effizienter verwalten können.
Derzeit ist es jedoch sehr zeitaufwendig und kompliziert, alle Einnahmen und Ausgaben manuell zu erfassen und zu analysieren.
Dadurch fehlt vielen Nutzern die Kontrolle über ihre Finanzen.

=== Aufgabenstellung

Eine App oder WebApp womit man mit Hilfe eines Barcode Scanners sofort die Inhaltsstoffe, Herkunft und Nachhaltigkeitsbewertung sehen kann.
Das erleichtert es unseren Kunden zu sehen das wir uns wirklich mit Nachhaltigkeit beschäftigen und Ihnen auch Einblicke dazu gewähren.

==== Funktionale Anforderungen

Unsere Software soll einer Person die Informationen über die Nachhaltigkeit eines Produktes liefern.
Sie können die Daten erhalten, indem sie den Barcode des Produkts scannen oder den Namen, Hersteller oder die Produkt Kategorie des Produktes eingeben.
Die Software soll auf eine Datenbank zugreifen können, in der Informationen zur Nachhaltigkeit von Produkten gespeichert sind.
Die Software soll die Nachhaltigkeitsdaten in einem strukturierten Format anzeigen.
Zusätzlich könnte z.B. ein Nachhaltigkeitsscore oder eine Einteilung in Kategorien („sehr nachhaltig“, „nachhaltig“, „wenig nachhaltig“)
angezeigt werden, damit der Nutzer die Informationen leicht einordnen kann.

==== Nichtfunktionale Anforderungen (NFA)

Die Benutzeroberfläche soll so gestaltet sein, dass auch unerfahrene Nutzer problemlos die benötigten Informationen finden und die Software bedienen können.
Sie wird auch ein einfaches, minimalistisches und strukturiertes Layout bekommen um es Kunden einfacher zu machen einen überblick zu bewahren.

=== Ziele
Mehr Menschen kaufen nachhaltiger ein, da es ihnen einfacher gemacht wird, die Nachhaltigkeit von Produkten zu überprüfen.
Dies kann dazu beitragen, den Klimawandel zu stoppen oder zumindest zu verlangsamen, wenn mehr Menschen einen nachhaltigen Lebensstil führen.


=== Mengengerüst
Die Datenbank sollte ungefähr 5000 Produkte mit Infos enthalten, diese können wir monatlich erweitern. Die App muss bis zu 500 Nutzern jeden Tag standhalten und die Produkdetails nach dem Scannen maximal 1-2 sekunden später anzeigen.

=== Rahmenbedingungen zB Vorgaben vom Auftraggeber
Die App soll auf IOS, Android und als Web-Version laufen. Er ist uns vorallem wichtig dass alle Datenschutzanforderungen nach DSGVO eingehalten werden.

