= Nachhaltigkeitstracker
FIndenig Leonie, Lena Graßauer, Lind Arifi

=== Ausgangssituation:
Viele Menschen haben Schwierigkeiten, ihre Finanzen im Blick zu behalten und ein effektives Budget zu verwalten. Besonders unerwartete Ausgaben oder fehlende Transparenz über laufende Kosten führen oft zu finanziellen Engpässen.

=== Problemstellung:

Wir möchten, dass unsere Nutzer auf einen Blick sehen können, wie viel Budget ihnen zur Verfügung steht, welche Ausgaben sie haben und wie sie ihre Finanzen effizienter verwalten können.
Derzeit ist es jedoch sehr zeitaufwendig und kompliziert, alle Einnahmen und Ausgaben manuell zu erfassen und zu analysieren.
Dadurch fehlt vielen Nutzern die Kontrolle über ihre Finanzen.

=== Aufgabenstellung

Eine App oder WebApp, mit der Nutzer ihre Einnahmen und Ausgaben verwalten und analysieren können.
Das erleichtert es unseren Kunden, ihre finanzielle Situation im Blick zu behalten und fundierte Entscheidungen zu treffen.

==== Funktionale Anforderungen

Unsere Software soll einer Person ermöglichen, ihre finanziellen Daten strukturiert zu erfassen und auszuwerten.
Sie können die Daten eingeben, indem sie manuell Einnahmen und Ausgaben erfassen oder bestehende Transaktionsdaten importieren.
Die Software soll auf eine Datenbank zugreifen können, in der finanzielle Informationen gespeichert und analysiert werden.
Die Software soll die Finanzdaten in einem strukturierten Format anzeigen.


==== Nichtfunktionale Anforderungen (NFA)

Die Benutzeroberfläche soll so gestaltet sein, dass auch unerfahrene Nutzer problemlos die benötigten Informationen finden und die Software bedienen können.
Sie wird auch ein einfaches, minimalistisches und strukturiertes Layout bekommen, um es Kunden einfacher zu machen einen überblick über ihre Finanzen zu bewahren. Unteranderem sollen die Benutzer auch diagramme über ihre Monatliche veränderungen, Ausgaben und Einnahmen sehen können.

=== Ziele
Mehr Menschen beginnen zu sparen da es ihnen viel einfacher fällt einen überblick über ihre Finanzen zu behalten. Dass führt dazu das Menschen gerade in jungen Jahren schon anfangen zu sparen und sich ein finanzielles Polster aufbauen.


=== Mengengerüst
Die Datenbank sollte ungefähr 5000 Produkte mit Infos enthalten, diese können wir monatlich erweitern. Die App muss bis zu 500 Nutzern jeden Tag standhalten und die Produkdetails nach dem Scannen maximal 1-2 sekunden später anzeigen.

=== Rahmenbedingungen zB Vorgaben vom Auftraggeber
Die App soll auf IOS, Android und als Web-Version laufen. Er ist uns vorallem wichtig dass alle Datenschutzanforderungen nach DSGVO eingehalten werden.

