= Nachhaltigkeitstracker
FIndenig Leonie, Lena Graßauer, Lind Arifi


== Pflichtenheft "Was mache ich"


=== Ausgangssituation
Unternehmen GoodFood in Leonding vielfaltige Auswahl an Lebensmiteln, 20 Mittarbeiter, Umweltbewusst

=== Problemstellung

Wir möchten das unsere Kunden die Nachhaltigkeit unserer Produkte sehen und unser Unternehmen dadurch transparenter wird.
Leider dauert es sehr lange bei jeden Produckt nachzuschauen wie Nachhaltig und gut es wirklich ist. Unsere Kunden stellen dadurch unsere Nachhaltigkeit öfter in Frage.


=== Aufgabenstellung

==== Funktionale Anforderungen

[plantuml,wireframe,png]
----
@startsalt
{
Name         | "                 "
Modifiers:   | { (X) public | () default | () private | () protected
	            [] abstract | [] final   | [] static }
Superclass:  | { "java.lang.Object " | [Browse...] }
}
@endsalt
----
==== Nichtfunktionale Anforderungen (NFA)
=== Ziele
=== Mengengerüst
=== Rahmenbedingungen
zB Vorgaben vom Auftraggeber

== Entwurf "Wie mache ich es"
=== Systemarchitektur
=== ...

== Projekthandbuch "Organisatorische Rahmenbedingungen"



=== GANTT-Diagramm

mit User-Stories (definiert in YouTrack)

[plantuml,gantt-protoype,png]
----
@startgantt
[Test prototype] lasts 10 days
[Prototype completed] happens at [Test prototype]'s end
[Setup assembly line] lasts 12 days
[Setup assembly line] starts at [Test prototype]'s end
[Test prototype 2] lasts 3 days
[Test prototype 2] starts at [Prototype completed]'s end
@endgantt
----



* link:minutes-of-meeting.html[Protokollvorlage]
* link:demo.html[Demo]

